name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # allow the bot to push to gh-pages

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # If you have a build step (e.g., npm run build), put it here.
      # - name: Build
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .   # change to ./dist if you build into /dist
